<a href="https://colab.research.google.com/gist/abhaykumart12/277a60a94d1cf005594e175f0eead83b/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Python**
1. Split this String

In [1]:
s = "Hi there Sam!"
arr=s.split(" ")
print(arr)

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string.
Output should be:The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {}  Kilometers".format(planet,diameter))

The diameter of Earth is 12742  Kilometers


3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
word = d['k1'][3]['tricky'][3]['target'][3]
print(word)

hello


Numpy


> 4.1 Create an array of 10 zeros?



In [6]:
import numpy as np
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



> 4.2 Create an array of 10 fives?



In [7]:
Fives = np.ones(10,dtype=int)*5
print(Fives)

[5 5 5 5 5 5 5 5 5 5]


5. Create an array of all the even integers from 20 to 35

In [8]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Concatenate a and b

> a = np.array([1, 2, 3]), b = np.array([4, 5, 6])



In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

Pandas
8. Create a dataframe with 3 rows and 2 columns

In [11]:
import pandas as pd

In [12]:
df={"Name":['ajay','mathew','mukesh'],
    "age":[21,20,20]}
df1=pd.DataFrame(df)
df1

Name  age
0    ajay   21
1  mathew   20
2  mukesh   20

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
import datetime
start=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
end=datetime.datetime.strptime("10-02-2023","%d-%m-%Y")
x=pd.date_range(start,end)
x

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

10. Create 2D list to DataFrame

In [14]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
arr=pd.DataFrame(lists)
arr

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24